seo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.core.urlresolvers import reverse


urlpatterns = patterns('',
                       url(r'^change_meta$', 'seo.views.change_meta', name="change_meta"),
)

callback/models.py
# -*- coding: utf-8 -*-


__author__ = 'hramik'
__author__ = 'hramik'

import datetime, sys, os
from django.utils.encoding import force_unicode

from django.db import models
# from markitup.fields import MarkupField
# from taggit.managers import TaggableManager
from django.forms import ModelForm
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from custom_sites.models import SiteInfo

from django.utils.translation import gettext_lazy as _

# from forms_builder.forms import models as fb_models
# from node import models as NodeModels

TOWATCH_STATUS_CHOICES = (
    ('W', 'ожидает'),
    ('R', 'перезвонить'),
    ('D', 'совершен'),
)


class Callback(models.Model):
    name = models.CharField(
            max_length=150,
            verbose_name='Your Name'
    )

    phone = models.CharField(
            max_length=20
    )

    call_time = models.CharField(
            max_length=150,
            blank=True
    )

    call_time = models.CharField(
            max_length=150,
            blank=True
    )

    email = models.EmailField(
            blank=True
    )

    status = models.CharField(
            max_length=1,
            choices=TOWATCH_STATUS_CHOICES,
            default="W"
    )

    comment = models.TextField(
            default="",
            blank=True
    )

    manager_comment = models.TextField(
            default="",
            blank=True
    )

    pub_date = models.DateTimeField(
            'date published',
            auto_now_add=True,
    )
    # pub_date.editable = True

    call_date = models.DateTimeField(
            'date call',
            blank=True,
            null=True,
            default=None,
    )

    site = models.ForeignKey(
            Site,
            blank=True,
            null=True,
            default=1,
            verbose_name=u'Сайт',
    )

    objects = models.Manager()
    on_site = CurrentSiteManager()

    def __unicode__(self):
        return self.name


class CallbackForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'ng-model': 'callback.name', 'required': 'True'}), label="Ваше имя")

    # site_id = forms.ModelChoiceField(
    #         # widget=forms.Select(attrs={'ng-model': 'callback.site'}),
    #         label="Сайт",
    #         to_field_name="id",
    #         queryset=Site.objects.all(),
    #         initial=SiteInfo.on_site.select_related().get().site.id,
    #         required=False)

    phone = forms.CharField(widget=forms.TextInput(attrs={'ng-model': 'callback.phone', 'required': 'True'}), label="Ваш телефон")

    call_time = forms.CharField(widget=forms.TextInput(attrs={'ng-model': 'callback.call_time'}), initial="", required=False, label="Время звонка")

    email = forms.EmailField(widget=forms.TextInput(attrs={'ng-model': 'callback.email', 'type': 'email'}), label="Email", required=False)

    class Meta:
        model = Callback
        fields = ('name', 'phone', 'call_time', 'email')

products/forms.py
# -*- coding: utf-8 -*-

import datetime, sys, os, re
from django.utils.encoding import force_unicode

from django.db import models
from django.forms import ModelForm
from django.db import models
from django import forms
from django.utils.translation import gettext_lazy as _
from products.models import *
from tri.models import *

from seo.models import *

'''
Форма комментария
'''


class BathFilterForm(ModelForm):
    hydromassage = forms.CharField(
        widget=forms.CheckboxInput(
            attrs={
                'class': '',
                'ng-model': 'global.filter.hydromassage',
            }
        ),
        label=u"Гидромассаж"
    )

    min_length = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': '',
                'ng-model': 'global.filter.min_length',
            }
        ),
        label=u"Минимальная длина",
        required=False
    )

    max_length = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': '',
                'ng-model': 'global.filter.max_length',
            }
        ),
        label=u"Максимальная длина",
        required=False
    )

    class Meta:
        model = SEOFields
        fields = ('hydromassage',)


class CreditOrderForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate[required]'}), label="Имя")
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate[required]'}), label=" Телефон")
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': ''}), label="Email")
    term = forms.ChoiceField(widget=forms.Select(attrs={'class': 'validate[required]'}),
                             choices=CREDIT_TERM_CHOICES, label="Срок страхования")
    first_pay_percent = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'validate[required]'}), label="Первый платеж (в процентах)")
    credit_type = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'validate[required]'}),
                                    choices=CREDIT_TYPE_CHOICES, label="Тип кредитования")
    agree = forms.ChoiceField(widget=forms.CheckboxInput(attrs={'class': 'validate[required]'}),
                              label=_("С условиями согласен"))

    class Meta:
        model = Credit
        fields = ('name', 'phone', 'email', 'term', 'first_pay_percent', 'credit_type')


class OrderForm(ModelForm):
    # poduct = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.product_id'}), label="",
    #                          required=False)
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.name', 'required': 'True', 'ng-initial': 'True'}),
        label="Ваше имя")

    address = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.address', 'ng-initial': 'True'}),
                              label="Адрес",
                              required=False)

    country = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.country', 'ng-initial': 'True'}),
                              label="Страна", required=False)

    index = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.index', 'ng-initial': 'True'}),
                           label="Индекс",
                           required=False)

    region = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.region', 'ng-initial': 'True'}),
                           label="Регион",
                           required=False)

    city = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.city', 'ng-initial': 'True'}),
                           label="Город",
                           required=False)

    street_abbr = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.street_abbr', 'ng-initial': 'True'}), required=False)

    street = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.street', 'ng-initial': 'True'}),
                           label="Улица",
                           required=False)

    house = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.house', 'ng-initial': 'True'}),
                           label="Дом",
                           required=False)

    destination = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.destination', 'ng-initial': 'True'}),
                           label="Расстояние",
                           required=False)

    phone = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.phone', 'required': 'True', 'ng-initial': 'True'}),
        label="Телефон")


    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': '', 'ng-model': 'quick_order.email', 'required': 'True', 'type': 'email', 'ng-initial': 'True'}), label="Email")

    comment = forms.CharField(widget=forms.Textarea(attrs={'class': '', 'ng-model': 'quick_order.comment', 'ng-initial': 'True'}),
                              label="Комментарий",
                              required=False)

    # call_value = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'ng-model': 'quick_order.call_value', 'required': 'True', 'ng-initial': 'True'}), label="")

    class Meta:
        model = Order
        fields = ('name', 'address', 'country', 'index', 'region', 'city',  'street_abbr', 'street', 'house', 'phone', 'email', 'comment')


from django.forms.extras.widgets import SelectDateWidget


class PayForm(ModelForm):
    delivery = forms.ModelChoiceField(queryset=Delivery.on_site.filter(publish=True),
                                      to_field_name="slug",
                                      # initial=Delivery.on_site.filter(publish=True)[0],
                                      widget=forms.Select(attrs={'class': '', 'icon-select': 'true', 'ng-model': 'pay_form.delivery', 'ng-initial': 'True',
                                                                 'ng-change': 'save();'}),
                                      label="Выберите способ доставки",
                                      required=False)

    carrier = forms.ModelChoiceField(queryset=Company.objects.filter(company_type__slug__in=('cargocarrier', 'distributor')),
                                     to_field_name="slug",
                                     # initial=Delivery.on_site.filter(publish=True)[0],
                                     widget=forms.Select(attrs={'class': '', 'ui-dropdown-o':
                                         'true', 'ng-model': 'pay_form.carrier', 'ng-initial': 'True', 'ng-change': 'save();'}),
                                     label="Перевозчик",
                                     required=False)

    carrier_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'ng-model': 'pay_form.carrier_number', 'ng-initial': 'True'}),
        label="Номер заявки перевозчика",
        required=False)

    need_cargo_service = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': '', 'ng-model': 'pay_form.need_cargo_service', 'ng-initial': 'True'}),
        label="Нужны услуги грузчиков(в т.ч. подъем на этаж)",
        required=False)

    version = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'ng-model': 'pay_form.version', 'ng-initial': 'True'}),
        label="Версия",
        required=False)

    delivery_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form_datetime', 'ng-model': 'pay_form.delivery_date', 'ng-initial': '', 'da-line-calendar': ""}),
        label="Дата отгрузки",
        required=False
    )

    PICKUP_TIME_PERIOD_CHOICES = (
        ('9_18', u'9-18'),
        ('9_13', u'9-13'),
        ('13_18', u'13-18'),
    )

    delivery_pickup_time_period = forms.ChoiceField(
        choices=PICKUP_TIME_PERIOD_CHOICES,
        widget=forms.Select(attrs={'class': 'ui  dropdown', 'ui-dropdown': 'true', 'ng-model': 'pay_form.delivery_pickup_time_period', 'ng-initial': 'True', 'ng-change': 'save();'}),
        label="Время отгрузки",
        required=False
    )

    custom_delivery_sum = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'ng-model': 'pay_form.custom_delivery_sum', 'ng-initial': 'True'}),
        label="Стоимость индивидуальной доставки",
        required=False)

    distributor = forms.ModelChoiceField(queryset=Company.objects.filter(company_type__slug='distributor'),
                                         to_field_name="slug",
                                         # initial=Delivery.on_site.filter(publish=True)[0],
                                         widget=forms.Select(
                                             attrs={'class': '', 'ui-dropdown-o': 'true', 'ng-model': 'pay_form.distributor', 'ng-initial': 'True', 'ng-change': 'save();'}),
                                         label="Дистрибьютор",
                                         required=False)

    # delivery_date = forms.ModelChoiceField(queryset=Company.objects.filter(company_type__slug='cargocarrier'),
    #                                   to_field_name="slug",
    #                                   # initial=Delivery.on_site.filter(publish=True)[0],
    #                                   widget=forms.Select(attrs={'class': '', 'ng-model': 'pay_form.delivery_date', 'ng-initial': 'True'}),
    #                                   label="Желаемая дата доставки",
    #                                   required=False)

    prepay = forms.ModelChoiceField(queryset=Prepay.objects.filter(publish=True),
                                    # initial=Prepay.objects.filter(publish=True)[0],
                                    to_field_name="slug",

templates/products/backoffice/backoffice.html
{% extends "triton_ua/tri_base.html" %}

{% load i18n %}
{% load thumbnail %}
{% load hramik_tags %}


{% block title %}{% trans "Triton" %} | Заказы{% endblock %}
{% block meta %}

{% endblock %}


{% block body_classes %}no-front two-col orderlist fluid{% endblock %}
{% block pagetitle %}
    {% if is_order %}Заказы{% endif %}
{% endblock %}

{% block intro %}
{% endblock %}

{% block controller %}
    ng-controller="ordersCtrl"
{% endblock %}

{% block content %}

    {% include "triton_ua/forms/form_base.html" with form=filter_form name_form='orders' submit_text="Фильтр" action='/orders' fields_class="inline fields" method='get' %}
    <a href="/orders">
        <i class="icon remove"></i>
        Сбросить фильры
    </a>

    <div class="ui top attached tabular menu" ng-init="active_tab='{{ active_tab }}';">
        <a class="item" ng-click="active_tab='orders'; changeURL('orders');" ng-class="{active: active_tab=='orders'}">
            Заказы
        </a>
        <a class="item" ng-click="active_tab='callbacks'; changeURL('callbacks');" ng-class="{active: active_tab=='callbacks'}">
            Звонки
        </a>
    </div>

    <div class="ui bottom attached segment">
        <div ng-show="active_tab=='orders'">
            {% include "products/backoffice/orders.html" %}
        </div>
        <div ng-show="active_tab=='callbacks'">
            {% include "products/backoffice/callbacks.html" %}
        </div>
    </div>

{% endblock %}


{% block sidebar %}


{% endblock %}

{% block extra_body %}
{% endblock %}

templates/products/backoffice/callbacks.html
<table class="ui celled structured  tablet stackable  table order_table">
    <thead>
    <tr>
        <th>Телефон</th>
        <th>Имя</th>
        <th>Время звонка</th>
        <th>Емейл</th>
        <th>Дата заявки</th>
        <th>Дата связи</th>
        <th>Комментарий</th>
        <th>Сайт</th>
        <th>Статус</th>
        {#                <th></th>#}
        {% if current_user.is_superuser %}
            <th>Вадминка</th>{% endif %}
    </tr>
    </thead>

    <tbody class="callbacks_table_tbody" hr-table-scroll-load=".callbacks_table_tbody" path="/callbacks">
    {% include "products/backoffice/callbacks_list.html" %}
    </tbody>

</table>

<div class="ui white modal callback" ng-controller="callbackCtr">
    <div class="center aligned content" style="text-align: center;">
        <h2 class="ui header"><a href="tel:{? global.callback.phone ?}">{? global.callback.phone ?}</a></h2>
        <h3 class="ui header">{? global.callback.name ?}</h3>
        <p>
        <div class="ui form">
            <div class="field">
                <textarea rows="3" ng-model="global.callback.manager_comment" style="border: 1px solid lightgray;"></textarea>
            </div>
        </div>
        </p>
    </div>

    <div class="actions">
        <div class="ui black deny button">
            Нет
        </div>
        <div class="ui red deny button" ng-click="done('R');" ng-class="{disabled: global.callback.manager_comment}">
            Перезвонить
        </div>
        <div class="ui positive right labeled icon button" ng-click="done('D');" ng-class="{disabled: !global.callback.manager_comment}">
            Да, контакт совершен
            <i class="checkmark icon"></i>
        </div>
    </div>
</div>

templates/products/backoffice/callbacks_list.html
{% load hramik_tags %}
{% for callback in callbacks %}
    <tr class="status_{? status ?}"
        ng-controller="callbackCtr"
        ng-click="set_current();"
        ng-init="id='{{ callback.id }}'; status='{{ callback.status }}'; phone='{{ callback.phone }}'; name='{{ callback.name }}'; comment='{{ callback.comment }}'; manager_comment=
    '{{ callback.manager_comment }}';">
        <td da-modal=".ui.modal.callback" class="nobr">
            <div class="ui header" ng-if="status=='W'">{{ callback.phone }}</div>
            <span ng-if="status!='W'">{{ callback.phone }}</span>
        </td>
        <td da-modal=".ui.modal.callback">{{ callback.name }}</td>
        <td da-modal=".ui.modal.callback">{{ callback.call_time }}</td>
        <td da-modal=".ui.modal.callback">{{ callback.email }}</td>
        <td da-modal=".ui.modal.callback">{{ callback.pub_date }}</td>
        <td da-modal=".ui.modal.callback">
            {% if callback.call_date %}
                {{ callback.call_date }} <span class="ui label">{{ callback.pub_date|timesince:callback.call_date }}</span>
            {% endif %}
        </td>
        <td da-modal=".ui.modal.callback">
            <div ng-bind-html="comment|newlines"></div>
            <div class="ui divider" ng-if="manager_comment"></div>
            <div ng-if="manager_comment" ng-bind-html="manager_comment|newlines"></div>
        </td>
        <td da-modal=".ui.modal.callback">{{ callback.site }}</td>

        <td>
            {{ callback.get_status_display }}
        </td>
        {#    <td class="center aligned">#}
        {#            <i class="ui check square icon" ng-click="global.callback.id = '{{ callback.id }}'; done('D');" style="cursor: pointer;" ng-if="status=='W'"></i>#}
        {#            <i class="ui minus outline square icon" ng-click="global.callback.id = '{{ callback.id }}'; done('W');" style="cursor: pointer;" ng-if="status=='D'"></i>#}
        {#    </td>#}
        {% if current_user.is_superuser %}
            <td><a href="{% url 'admin:callback_callback_change' callback.id %}" target="_blank">админка</a></td>{% endif %}
    </tr>
{% endfor %}

templates/products/backoffice/orders.html
{% load i18n %}
{% load thumbnail %}
{% load hramik_tags %}



<table class="ui celled structured table order_table">
    <thead>
    <tr>
        <th rowspan="2">№</th>
        <th rowspan="2">Статус</th>
        <th colspan="10">Данные заказа</th>
        <th colspan="4">Предоплата</th>
        <th colspan="7">Доставка</th>
        <th rowspan="2">Доплата</th>
        <th rowspan="2">Бонус</th>

    </tr>
    <tr>
        <th>Дата</th>
        <th>Сайт</th>
        <th>Фио</th>
        <th>Телефон</th>
        <th>Емайл</th>
        <th>Товар</th>
        <th>Примечания</th>
        <th>Стоимость товара</th>
        <th>Стоимость доставки</th>
        <th>Сумма заказа</th>
        <th>Предоплата</th>
        <th>Сумма предоплаты</th>
        <th>Платежный агент</th>
        <th>Инвойс</th>
        <th>ID</th>
        <th>Дата отгрузки</th>
        <th>Дистрибьютор</th>
        <th>Адрес доставки</th>
        <th>Перевозчик</th>
        <th>Номер заказа</th>
        <th>Цена доставки</th>
    </tr>
    </thead>

    <tbody class="order_table_tbody" hr-table-scroll-load=".order_table_tbody"  path="/orders">
    {% include "products/backoffice/orders_sum.html" %}
    {% include "products/backoffice/orders_list.html" %}
    </tbody>

</table>

templates/products/backoffice/orders_list.html
{% load hramik_tags %}
{% for order in orders %}

    <tr class="status_{{ order.status }}">
        <td>
            {% if debug %}
                <a href="http://127.0.0.1:8000/order{{ order.hash }}" target="_blank">{{ order.im_id }}</a>
            {% else %}
                <a href="http://{{ order.site.domain }}/order{{ order.hash }}" target="_blank">{{ order.im_id }}</a>
            {% endif %}
        </td>
        <td style="text-align: center;"><i
                class="ui icon {% if order.status == 'CO' %}check{% elif order.status == 'NO' %}circle{% elif order.status == 'CA' %}remove{% elif order.status == 'SA' %}bookmark{% elif order.status == 'PR' %}visa{% elif order.status == 'PA' %}money{% elif order.status == 'EX' %}archive{% elif order.status == 'SH' %}truck{% elif order.status == 'DE' %}smile{% endif %}"></i>
        <div class="small">{% if order.status == 'CO' %}полностью оплачен{% elif order.status == 'NO' %}новый{% elif order.status == 'CA' %}отменен{% elif order.status == 'SA' %}оформлен{% elif order.status == 'PR' %}отправлен на предоплату{% elif order.status == 'PA' %}предоплачен{% elif order.status == 'EX' %}отправлен на исполнение{% elif order.status == 'SH' %}отгружен{% elif order.status == 'DE' %}доставлен{% endif %}</div>
        </td>
        <td>{{ order.pub_date }}</td>
        <td>{{ order.site }}</td>
        <td>{{ order.name }}</td>
        <td>{{ order.phone }}</td>
        <td>{{ order.email }}</td>
        <td>
            {% if order.products %}
                {{ order.products|safe }}
            {% else %}
                {% for orderitem in order.order_items.all %}
                    <div class="">{{ orderitem.product.title }} </div>
                {% endfor %}
            {% endif %}
        </td>
        <td style="font-size: .8rem; line-height: 1rem;">{{ order.comment }}</td>
        <td><s>{{ order.cart_sum_end }}</s><br/>{{ order.price }}</td>
        <td>{% if order.delivery_sum %}
            {{ order.delivery_sum }}
        {% else %}
            {{ order.delivery.price }}
        {% endif %}</td>
        <td>{{ order.price }}</td>
        <td>{{ order.prepay }}</td>
        <td>
            {{ order.order_sum_amount }}<br>
            {{ order.additional_order_sum_amount }}<br>
        </td>

        <td>{{ order.pay_agent }}</td>
        <td>
            {{ order.invoice_id }}<br>
            {{ order.additional_invoice_id }}
        </td>

        <td>{{ order.delivery_did }}</td>
        <td>{{ order.delivery_date }}</td>
        <td>{{ order.distributor }}</td>
        <td>{{ order.get_address }}</td>
        <td>{{ order.carrier }}</td>
        <td>
            {% for delivery in order.delivery_operations %}
                {{ delivery.carrier_number }}
            {% endfor %}
            {% if order.delivery_operations.count > 1 %}
                <div class="ui divider"></div>
                &nbsp;
            {% endif %}
        </td>
        <td>
            {% for delivery in order.delivery_operations %}
                {{ delivery.delivery_price }}
            {% endfor %}

            {% if order.delivery_operations.count > 1 %}
                <div class="ui divider"></div>
                <b>{{ order.delivery_operations | delivery_sum }}</b>
            {% endif %}

        </td>
        <td>{{ order.additional_sum }}</td>
        <td>
            {% if perms.products.can_view_bonus %}
                {% if order.bonus %}
                    {{ order.bonus }}
                {% else %}
                    {{ order.get_bonus }}
                {% endif %}
            {% endif %}
        </td>
    </tr>
{% endfor %}

templates/products/backoffice/orders_sum.html
{% load hramik_tags %}

    <tr class="sum active" style="font-weight: bold;">
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="ui header" nowrap><s>{{ sum.cart_sum_end__sum | price }}</s><br/>
            {{ sum.price__sum | price}}</td>
        <td  class="ui header" nowrap>
            {{ sum.delivery_sum__sum | price }}
        </td>
        <td  class="ui header" nowrap>{{ sum.price__sum | price }}</td>
        <td></td>
        <td  class="ui header" nowrap>{{ sum.order_sum_amount__sum | price }}<br>{{ sum.additional_order_sum_amount__sum | price }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td  class="ui header" nowrap>{{ sum.additional_sum }}</td>
        <td  class="ui header" nowrap>
            {% if perms.products.can_view_bonus %}
                {{ sum.bonus__sum | price }}
            {% endif %}
        </td>
    </tr>